apiVersion: batch/v1
kind: Job
metadata:
  name: build-test
spec:
  template:
    spec:
      initContainers:
        - name: test
          image: busybox
          command: ["sh", "-c", "sleep 10 && echo START"]
      containers:
      - name: pi
        image: perl:5.34
        command: ["perl",  "-Mbignum=bpi", "-wle", "'print bpi(2000)'"]
      restartPolicy: Never
  backoffLimit: 1