apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
    # see buildkit/docs/rootless.md for caveats of rootless mode
    spec:
      initContainers:         
        - name: init-sysctl
          image: busybox
          command:
          - /bin/sh
          - -c
          - sysctl -w vm.vfs_cache_pressure=500
          securityContext:
            privileged: true
      containers:
        - name: buildkitd
          volumeMounts:
            - name: buildkit-storage
              mountPath: /var/lib/buildkit
          resources: {}
          image: moby/buildkit:v0.10.3
          resources:
            # limits:
            #   memory: "600Mi"
            #   cpu: "600m"
            requests:
              memory: "600Mi"
              cpu: "600m"
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            # - --oci-worker-no-process-sandbox
          # the probe below will only work after Release v0.6.3
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          # the probe below will only work after Release v0.6.3
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
          ports:
            - containerPort: 1234
      volumes:
        - name: buildkit-storage
          persistentVolumeClaim:
            claimName: buildkit-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  ports:
    - port: 1234
      protocol: TCP
  selector:
    app: buildkitd