version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "staging"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "staging"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
    target-branch: "staging"
