version = 1

test_patterns = [
  "**/*_test.go",
]

exclude_patterns = [
  "vendor/**",
]

[[analyzers]]
  name = "docker"
  enabled = true

[[analyzers]]
  name = "go"
  enabled = true

  [analyzers.meta]
    dependencies_vendored = true
    import_path = "github.com/convox/convox"

[[analyzers]]
  name = "terraform"
  enabled = true
