run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  enable:
    - errcheck
    - staticcheck
    - gosec
    - govet
    - bodyclose
    - nilerr
    - exhaustive
    - gocritic
    - goimports
    - ineffassign
    - unused
  disable:
    - lll
    - wsl
    - funlen
    - gocognit
    - godot
    - godox
    - wrapcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gosec:
    excludes:
      - G104
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-tags:
      - style
      - opinionated
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
