# FROM golang:1.16-alpine AS package
# # FROM golang:1.16 AS package

# # RUN apt-get update && apt-get -y install upx-ucl
# RUN apk update && apk add make gcc linux-headers libc-dev

# WORKDIR /usr/src/convox

# COPY . .

# ENV GODEBUG=http2client=0
# RUN make $GOPATH/bin/build

# Use this FROM instruction as shortcut to use --copy=from kaniko below
# It's also possible to use directly COPY --from=gcr.io/kaniko-project/executor
# FROM gcr.io/kaniko-project/executor AS kaniko
FROM gcr.io/kaniko-project/executor

# FROM alpine:3.14.2
# FROM ubuntu:18.04

# RUN apk --update add \
#   curl \
#   git

# RUN apt update && apt install git curl -y

COPY kaniko-bug /workspace

#
# Add kaniko to this image by re-using binaries and steps from official image
#
# ENV GODEBUG=http2client=0
# COPY executor /kaniko/executor

# COPY --from=kaniko /kaniko/executor /kaniko/executor
# COPY --from=kaniko /kaniko/docker-credential-gcr /kaniko/docker-credential-gcr
# COPY --from=kaniko /kaniko/docker-credential-ecr-login /kaniko/docker-credential-ecr-login
# COPY --from=kaniko /kaniko/docker-credential-acr-env /kaniko/docker-credential-acr-env
# COPY --from=kaniko /etc/nsswitch.conf /etc/nsswitch.conf
# COPY --from=kaniko /kaniko/.docker /kaniko/.docker

COPY do-creds.json /kaniko/.docker/config.json

# COPY --from=package /go/bin/build /usr/bin

# ENV PATH $PATH:/kaniko