services:
  web:
    image: httpd
    port: 80
  worker:
    build: ./worker

timers:
  cleanup:
    command: ./cmd.sh
    schedule: "* * * * *"
    service: worker
  concurrency-allowed:
    command: ./long-cmd.sh
    schedule: "* * * * *"
    service: worker
    concurrencyPolicy: Allow
  concurrency-forbid:
    command: ./long-cmd.sh
    schedule: "* * * * *"
    service: worker
    concurrencyPolicy: Forbid
