resources:
  postgresdb:
    type: postgres
  rediscache:
    type: redis
  memcache:
    type: memcached
  mysqldb:
    type: mysql
  mariadb:
    type: mariadb
services:
  web:
    build: .
    port: 80
    resources:
      - postgresdb:DB_URL
      - rediscache:REDIS_URL
      - memcache:MEMCACHE_URL
      - mysqldb:MYSQL_URL
      - mariadb:MARIA_URL
timers:
  example:
    command: /usr/scripts/timer_cmd.sh
    schedule: "* * * * *"
    service: web
