resources:
  one:
    type: postgres
  postgresdb:
    type: postgres
  rediscache:
    type: redis
  memcache:
    type: memcached
    options:
      version: 1.6.17
  mysqldb:
    type: mysql
    options:
      version: 8.0.30
  mariadb:
    type: mariadb
services:
  web:
    build: .
    port: 80
    resources:
      - postgresdb:DB_URL
      - rediscache:REDIS_URL
      - memcache:MEMCACHE_URL
      - mysqldb:MYSQL_URL
      - mariadb:MARIA_URL
      - one
timers:
  example:
    command: /usr/scripts/timer_cmd.sh
    schedule: "* * * * *"
    service: web
  concurrencyallowed:
    command: /usr/scripts/timer_long_cmd.sh
    schedule: "* * * * *"
    service: web
    concurrency: allow
  concurrencyforbid:
    command: /usr/scripts/timer_long_cmd.sh
    schedule: "* * * * *"
    service: web
    concurrency: forbid
