resources:
  postgresdb:
    type: postgres
  rediscache:
    type: redis
services:
  web:
    build: .
    port: 80
    resources:
      - postgresdb:DB_URL
      - rediscache:REDIS_URL

timers:
  example:
    command: /usr/scripts/timer_cmd.sh
    schedule: "* * * * *"
    service: web
  concurrencyallowed:
    command: /usr/scripts/timer_long_cmd.sh
    schedule: "* * * * *"
    service: web
    concurrencyPolicy: Allow
  concurrencyforbid:
    command: /usr/scripts/timer_long_cmd.sh
    schedule: "* * * * *"
    service: web
    concurrencyPolicy: Forbid
