resources:
  postgresdb:
    type: postgres
  rediscache:
    type: redis
  memcache:
    type: memcached
services:
  web:
    build: .
    port: 80
    resources:
      - postgresdb:DB_URL
      - rediscache:REDIS_URL
      - memcache:MEMCACHE_URL

timers:
  example:
    command: /usr/scripts/timer_cmd.sh
    schedule: "* * * * *"
    service: web
