/*

Copyright 2020 Convox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	atomv1 "github.com/convox/convox/pkg/atom/pkg/apis/atom/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAtomVersions implements AtomVersionInterface
type FakeAtomVersions struct {
	Fake *FakeAtomV1
	ns   string
}

var atomversionsResource = schema.GroupVersionResource{Group: "atom.convox.com", Version: "v1", Resource: "atomversions"}

var atomversionsKind = schema.GroupVersionKind{Group: "atom.convox.com", Version: "v1", Kind: "AtomVersion"}

// Get takes name of the atomVersion, and returns the corresponding atomVersion object, and an error if there is any.
func (c *FakeAtomVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *atomv1.AtomVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(atomversionsResource, c.ns, name), &atomv1.AtomVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*atomv1.AtomVersion), err
}

// List takes label and field selectors, and returns the list of AtomVersions that match those selectors.
func (c *FakeAtomVersions) List(ctx context.Context, opts v1.ListOptions) (result *atomv1.AtomVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(atomversionsResource, atomversionsKind, c.ns, opts), &atomv1.AtomVersionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &atomv1.AtomVersionList{ListMeta: obj.(*atomv1.AtomVersionList).ListMeta}
	for _, item := range obj.(*atomv1.AtomVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested atomVersions.
func (c *FakeAtomVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(atomversionsResource, c.ns, opts))

}

// Create takes the representation of a atomVersion and creates it.  Returns the server's representation of the atomVersion, and an error, if there is any.
func (c *FakeAtomVersions) Create(ctx context.Context, atomVersion *atomv1.AtomVersion, opts v1.CreateOptions) (result *atomv1.AtomVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(atomversionsResource, c.ns, atomVersion), &atomv1.AtomVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*atomv1.AtomVersion), err
}

// Update takes the representation of a atomVersion and updates it. Returns the server's representation of the atomVersion, and an error, if there is any.
func (c *FakeAtomVersions) Update(ctx context.Context, atomVersion *atomv1.AtomVersion, opts v1.UpdateOptions) (result *atomv1.AtomVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(atomversionsResource, c.ns, atomVersion), &atomv1.AtomVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*atomv1.AtomVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAtomVersions) UpdateStatus(ctx context.Context, atomVersion *atomv1.AtomVersion, opts v1.UpdateOptions) (*atomv1.AtomVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(atomversionsResource, "status", c.ns, atomVersion), &atomv1.AtomVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*atomv1.AtomVersion), err
}

// Delete takes name of the atomVersion and deletes it. Returns an error if one occurs.
func (c *FakeAtomVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(atomversionsResource, c.ns, name), &atomv1.AtomVersion{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAtomVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(atomversionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &atomv1.AtomVersionList{})
	return err
}

// Patch applies the patch and returns the patched atomVersion.
func (c *FakeAtomVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *atomv1.AtomVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(atomversionsResource, c.ns, name, pt, data, subresources...), &atomv1.AtomVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*atomv1.AtomVersion), err
}
