/*

Copyright 2020 Convox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AtomVersionSpecApplyConfiguration represents an declarative configuration of the AtomVersionSpec type for use
// with apply.
type AtomVersionSpecApplyConfiguration struct {
	Release    *string `json:"release,omitempty"`
	Template   []byte  `json:"template,omitempty"`
	Conditions *string `json:"conditions,omitempty"`
}

// AtomVersionSpecApplyConfiguration constructs an declarative configuration of the AtomVersionSpec type for use with
// apply.
func AtomVersionSpec() *AtomVersionSpecApplyConfiguration {
	return &AtomVersionSpecApplyConfiguration{}
}

// WithRelease sets the Release field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Release field is set to the value of the last call.
func (b *AtomVersionSpecApplyConfiguration) WithRelease(value string) *AtomVersionSpecApplyConfiguration {
	b.Release = &value
	return b
}

// WithTemplate adds the given value to the Template field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Template field.
func (b *AtomVersionSpecApplyConfiguration) WithTemplate(values ...byte) *AtomVersionSpecApplyConfiguration {
	for i := range values {
		b.Template = append(b.Template, values[i])
	}
	return b
}

// WithConditions sets the Conditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conditions field is set to the value of the last call.
func (b *AtomVersionSpecApplyConfiguration) WithConditions(value string) *AtomVersionSpecApplyConfiguration {
	b.Conditions = &value
	return b
}
