/*

Copyright 2020 Convox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AtomSpecApplyConfiguration represents an declarative configuration of the AtomSpec type for use
// with apply.
type AtomSpecApplyConfiguration struct {
	Conditions              []AtomConditionApplyConfiguration `json:"conditions,omitempty"`
	CurrentVersion          *string                           `json:"currentVersion,omitempty"`
	PreviousVersion         *string                           `json:"previousVersion,omitempty"`
	ProgressDeadlineSeconds *int32                            `json:"progressDeadlineSeconds,omitempty"`
}

// AtomSpecApplyConfiguration constructs an declarative configuration of the AtomSpec type for use with
// apply.
func AtomSpec() *AtomSpecApplyConfiguration {
	return &AtomSpecApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *AtomSpecApplyConfiguration) WithConditions(values ...*AtomConditionApplyConfiguration) *AtomSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithCurrentVersion sets the CurrentVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentVersion field is set to the value of the last call.
func (b *AtomSpecApplyConfiguration) WithCurrentVersion(value string) *AtomSpecApplyConfiguration {
	b.CurrentVersion = &value
	return b
}

// WithPreviousVersion sets the PreviousVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreviousVersion field is set to the value of the last call.
func (b *AtomSpecApplyConfiguration) WithPreviousVersion(value string) *AtomSpecApplyConfiguration {
	b.PreviousVersion = &value
	return b
}

// WithProgressDeadlineSeconds sets the ProgressDeadlineSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressDeadlineSeconds field is set to the value of the last call.
func (b *AtomSpecApplyConfiguration) WithProgressDeadlineSeconds(value int32) *AtomSpecApplyConfiguration {
	b.ProgressDeadlineSeconds = &value
	return b
}
