/*

Copyright 2020 Convox, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AtomConditionApplyConfiguration represents an declarative configuration of the AtomCondition type for use
// with apply.
type AtomConditionApplyConfiguration struct {
	ApiVersion *string                                         `json:"apiVersion,omitempty"`
	Conditions map[string]AtomConditionMatchApplyConfiguration `json:"conditions,omitempty"`
	Kind       *string                                         `json:"kind,omitempty"`
	Name       *string                                         `json:"name,omitempty"`
	Namespace  *string                                         `json:"namespace,omitempty"`
}

// AtomConditionApplyConfiguration constructs an declarative configuration of the AtomCondition type for use with
// apply.
func AtomCondition() *AtomConditionApplyConfiguration {
	return &AtomConditionApplyConfiguration{}
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *AtomConditionApplyConfiguration) WithApiVersion(value string) *AtomConditionApplyConfiguration {
	b.ApiVersion = &value
	return b
}

// WithConditions puts the entries into the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Conditions field,
// overwriting an existing map entries in Conditions field with the same key.
func (b *AtomConditionApplyConfiguration) WithConditions(entries map[string]AtomConditionMatchApplyConfiguration) *AtomConditionApplyConfiguration {
	if b.Conditions == nil && len(entries) > 0 {
		b.Conditions = make(map[string]AtomConditionMatchApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Conditions[k] = v
	}
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *AtomConditionApplyConfiguration) WithKind(value string) *AtomConditionApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AtomConditionApplyConfiguration) WithName(value string) *AtomConditionApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *AtomConditionApplyConfiguration) WithNamespace(value string) *AtomConditionApplyConfiguration {
	b.Namespace = &value
	return b
}
