apiVersion: v1
kind: Service
metadata:
  name: registry-out
  namespace: heron-test-do-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    service: registry
    system: convox
  sessionAffinity: None
  type: LoadBalancer
