package billing

type InstancePrice struct {
	OnDemandUsdPerHour   float64
	SpotUsdPerHourFactor float64
	GpuCount             int
	GpuType              string
	VcpuCount            int
	MemGb                float64
}

// SpotDefaultFactor approximates the ~70% spot discount across stable families.
const SpotDefaultFactor = 0.30

const pricingTableVersion = "2026-07-16"

const PricingSourceStaticTable = "on-demand-static-table"

// Code generated by go run ./pkg/billing/gen aws on 2026-07-16 from aws_ec2_useast1.json. DO NOT EDIT by hand.
var InstancePricing = map[string]InstancePrice{
	// GPU: g4dn (T4)
	"g4dn.xlarge":   {OnDemandUsdPerHour: 0.526, GpuCount: 1, GpuType: "T4", VcpuCount: 4, MemGb: 16},
	"g4dn.2xlarge":  {OnDemandUsdPerHour: 0.752, GpuCount: 1, GpuType: "T4", VcpuCount: 8, MemGb: 32},
	"g4dn.4xlarge":  {OnDemandUsdPerHour: 1.204, GpuCount: 1, GpuType: "T4", VcpuCount: 16, MemGb: 64},
	"g4dn.8xlarge":  {OnDemandUsdPerHour: 2.176, GpuCount: 1, GpuType: "T4", VcpuCount: 32, MemGb: 128},
	"g4dn.12xlarge": {OnDemandUsdPerHour: 3.912, GpuCount: 4, GpuType: "T4", VcpuCount: 48, MemGb: 192},
	"g4dn.16xlarge": {OnDemandUsdPerHour: 4.352, GpuCount: 1, GpuType: "T4", VcpuCount: 64, MemGb: 256},
	"g4dn.metal":    {OnDemandUsdPerHour: 7.824, GpuCount: 8, GpuType: "T4", VcpuCount: 96, MemGb: 384},

	// GPU: g4ad (V520)
	"g4ad.xlarge":   {OnDemandUsdPerHour: 0.37853, GpuCount: 1, GpuType: "V520", VcpuCount: 4, MemGb: 16},
	"g4ad.2xlarge":  {OnDemandUsdPerHour: 0.54117, GpuCount: 1, GpuType: "V520", VcpuCount: 8, MemGb: 32},
	"g4ad.4xlarge":  {OnDemandUsdPerHour: 0.867, GpuCount: 1, GpuType: "V520", VcpuCount: 16, MemGb: 64},
	"g4ad.8xlarge":  {OnDemandUsdPerHour: 1.734, GpuCount: 2, GpuType: "V520", VcpuCount: 32, MemGb: 128},
	"g4ad.16xlarge": {OnDemandUsdPerHour: 3.468, GpuCount: 4, GpuType: "V520", VcpuCount: 64, MemGb: 256},

	// GPU: g5 (A10G)
	"g5.xlarge":   {OnDemandUsdPerHour: 1.006, GpuCount: 1, GpuType: "A10G", VcpuCount: 4, MemGb: 16},
	"g5.2xlarge":  {OnDemandUsdPerHour: 1.212, GpuCount: 1, GpuType: "A10G", VcpuCount: 8, MemGb: 32},
	"g5.4xlarge":  {OnDemandUsdPerHour: 1.624, GpuCount: 1, GpuType: "A10G", VcpuCount: 16, MemGb: 64},
	"g5.8xlarge":  {OnDemandUsdPerHour: 2.448, GpuCount: 1, GpuType: "A10G", VcpuCount: 32, MemGb: 128},
	"g5.12xlarge": {OnDemandUsdPerHour: 5.672, GpuCount: 4, GpuType: "A10G", VcpuCount: 48, MemGb: 192},
	"g5.16xlarge": {OnDemandUsdPerHour: 4.096, GpuCount: 1, GpuType: "A10G", VcpuCount: 64, MemGb: 256},
	"g5.24xlarge": {OnDemandUsdPerHour: 8.144, GpuCount: 4, GpuType: "A10G", VcpuCount: 96, MemGb: 384},
	"g5.48xlarge": {OnDemandUsdPerHour: 16.288, GpuCount: 8, GpuType: "A10G", VcpuCount: 192, MemGb: 768},

	// GPU: g5g (T4G)
	"g5g.xlarge":   {OnDemandUsdPerHour: 0.42, GpuCount: 1, GpuType: "T4G", VcpuCount: 4, MemGb: 8},
	"g5g.2xlarge":  {OnDemandUsdPerHour: 0.556, GpuCount: 1, GpuType: "T4G", VcpuCount: 8, MemGb: 16},
	"g5g.4xlarge":  {OnDemandUsdPerHour: 0.828, GpuCount: 1, GpuType: "T4G", VcpuCount: 16, MemGb: 32},
	"g5g.8xlarge":  {OnDemandUsdPerHour: 1.372, GpuCount: 1, GpuType: "T4G", VcpuCount: 32, MemGb: 64},
	"g5g.16xlarge": {OnDemandUsdPerHour: 2.744, GpuCount: 2, GpuType: "T4G", VcpuCount: 64, MemGb: 128},
	"g5g.metal":    {OnDemandUsdPerHour: 2.744, GpuCount: 2, GpuType: "T4G", VcpuCount: 64, MemGb: 128},

	// GPU: g6 (L4)
	"g6.xlarge":   {OnDemandUsdPerHour: 0.8048, GpuCount: 1, GpuType: "L4", VcpuCount: 4, MemGb: 16},
	"g6.2xlarge":  {OnDemandUsdPerHour: 0.9776, GpuCount: 1, GpuType: "L4", VcpuCount: 8, MemGb: 32},
	"g6.4xlarge":  {OnDemandUsdPerHour: 1.3232, GpuCount: 1, GpuType: "L4", VcpuCount: 16, MemGb: 64},
	"g6.8xlarge":  {OnDemandUsdPerHour: 2.0144, GpuCount: 1, GpuType: "L4", VcpuCount: 32, MemGb: 128},
	"g6.12xlarge": {OnDemandUsdPerHour: 4.6016, GpuCount: 4, GpuType: "L4", VcpuCount: 48, MemGb: 192},
	"g6.16xlarge": {OnDemandUsdPerHour: 3.3968, GpuCount: 1, GpuType: "L4", VcpuCount: 64, MemGb: 256},
	"g6.24xlarge": {OnDemandUsdPerHour: 6.6752, GpuCount: 4, GpuType: "L4", VcpuCount: 96, MemGb: 384},
	"g6.48xlarge": {OnDemandUsdPerHour: 13.3504, GpuCount: 8, GpuType: "L4", VcpuCount: 192, MemGb: 768},

	// GPU: g6e (L40S)
	"g6e.xlarge":   {OnDemandUsdPerHour: 1.861, GpuCount: 1, GpuType: "L40S", VcpuCount: 4, MemGb: 32},
	"g6e.2xlarge":  {OnDemandUsdPerHour: 2.24208, GpuCount: 1, GpuType: "L40S", VcpuCount: 8, MemGb: 64},
	"g6e.4xlarge":  {OnDemandUsdPerHour: 3.00424, GpuCount: 1, GpuType: "L40S", VcpuCount: 16, MemGb: 128},
	"g6e.8xlarge":  {OnDemandUsdPerHour: 4.52856, GpuCount: 1, GpuType: "L40S", VcpuCount: 32, MemGb: 256},
	"g6e.12xlarge": {OnDemandUsdPerHour: 10.49264, GpuCount: 4, GpuType: "L40S", VcpuCount: 48, MemGb: 384},
	"g6e.16xlarge": {OnDemandUsdPerHour: 7.57719, GpuCount: 1, GpuType: "L40S", VcpuCount: 64, MemGb: 512},
	"g6e.24xlarge": {OnDemandUsdPerHour: 15.06559, GpuCount: 4, GpuType: "L40S", VcpuCount: 96, MemGb: 768},
	"g6e.48xlarge": {OnDemandUsdPerHour: 30.13118, GpuCount: 8, GpuType: "L40S", VcpuCount: 192, MemGb: 1536},

	// GPU: p3 (V100)
	"p3.2xlarge":  {OnDemandUsdPerHour: 3.06, GpuCount: 1, GpuType: "V100", VcpuCount: 8, MemGb: 61},
	"p3.8xlarge":  {OnDemandUsdPerHour: 12.24, GpuCount: 4, GpuType: "V100", VcpuCount: 32, MemGb: 244},
	"p3.16xlarge": {OnDemandUsdPerHour: 24.48, GpuCount: 8, GpuType: "V100", VcpuCount: 64, MemGb: 488},

	// GPU: p4d (A100)
	"p4d.24xlarge": {OnDemandUsdPerHour: 21.957642, GpuCount: 8, GpuType: "A100", VcpuCount: 96, MemGb: 1152},

	// GPU: p5 (H100)
	"p5.48xlarge": {OnDemandUsdPerHour: 55.04, GpuCount: 8, GpuType: "H100", VcpuCount: 192, MemGb: 2048},

	// Neuron: inf1 (Inferentia1)
	"inf1.xlarge":   {OnDemandUsdPerHour: 0.228, GpuCount: 1, GpuType: "Inferentia1", VcpuCount: 4, MemGb: 8},
	"inf1.2xlarge":  {OnDemandUsdPerHour: 0.362, GpuCount: 1, GpuType: "Inferentia1", VcpuCount: 8, MemGb: 16},
	"inf1.6xlarge":  {OnDemandUsdPerHour: 1.18, GpuCount: 4, GpuType: "Inferentia1", VcpuCount: 24, MemGb: 48},
	"inf1.24xlarge": {OnDemandUsdPerHour: 4.721, GpuCount: 16, GpuType: "Inferentia1", VcpuCount: 96, MemGb: 192},

	// Neuron: inf2 (Inferentia2)
	"inf2.xlarge":   {OnDemandUsdPerHour: 0.7582, GpuCount: 1, GpuType: "Inferentia2", VcpuCount: 4, MemGb: 16},
	"inf2.8xlarge":  {OnDemandUsdPerHour: 1.96786, GpuCount: 1, GpuType: "Inferentia2", VcpuCount: 32, MemGb: 128},
	"inf2.24xlarge": {OnDemandUsdPerHour: 6.49063, GpuCount: 6, GpuType: "Inferentia2", VcpuCount: 96, MemGb: 384},
	"inf2.48xlarge": {OnDemandUsdPerHour: 12.98127, GpuCount: 12, GpuType: "Inferentia2", VcpuCount: 192, MemGb: 768},

	// Neuron: trn1 (Trainium1)
	"trn1.2xlarge":  {OnDemandUsdPerHour: 1.34375, GpuCount: 1, GpuType: "Trainium1", VcpuCount: 8, MemGb: 32},
	"trn1.32xlarge": {OnDemandUsdPerHour: 21.5, GpuCount: 16, GpuType: "Trainium1", VcpuCount: 128, MemGb: 512},

	// CPU general: m5
	"m5.large":    {OnDemandUsdPerHour: 0.096, VcpuCount: 2, MemGb: 8},
	"m5.xlarge":   {OnDemandUsdPerHour: 0.192, VcpuCount: 4, MemGb: 16},
	"m5.2xlarge":  {OnDemandUsdPerHour: 0.384, VcpuCount: 8, MemGb: 32},
	"m5.4xlarge":  {OnDemandUsdPerHour: 0.768, VcpuCount: 16, MemGb: 64},
	"m5.8xlarge":  {OnDemandUsdPerHour: 1.536, VcpuCount: 32, MemGb: 128},
	"m5.12xlarge": {OnDemandUsdPerHour: 2.304, VcpuCount: 48, MemGb: 192},
	"m5.16xlarge": {OnDemandUsdPerHour: 3.072, VcpuCount: 64, MemGb: 256},
	"m5.24xlarge": {OnDemandUsdPerHour: 4.608, VcpuCount: 96, MemGb: 384},

	// CPU general: m5a
	"m5a.large":    {OnDemandUsdPerHour: 0.086, VcpuCount: 2, MemGb: 8},
	"m5a.xlarge":   {OnDemandUsdPerHour: 0.172, VcpuCount: 4, MemGb: 16},
	"m5a.2xlarge":  {OnDemandUsdPerHour: 0.344, VcpuCount: 8, MemGb: 32},
	"m5a.4xlarge":  {OnDemandUsdPerHour: 0.688, VcpuCount: 16, MemGb: 64},
	"m5a.8xlarge":  {OnDemandUsdPerHour: 1.376, VcpuCount: 32, MemGb: 128},
	"m5a.12xlarge": {OnDemandUsdPerHour: 2.064, VcpuCount: 48, MemGb: 192},
	"m5a.16xlarge": {OnDemandUsdPerHour: 2.752, VcpuCount: 64, MemGb: 256},
	"m5a.24xlarge": {OnDemandUsdPerHour: 4.128, VcpuCount: 96, MemGb: 384},

	// CPU general: m5n (network-optimized)
	"m5n.large":    {OnDemandUsdPerHour: 0.119, VcpuCount: 2, MemGb: 8},
	"m5n.xlarge":   {OnDemandUsdPerHour: 0.238, VcpuCount: 4, MemGb: 16},
	"m5n.2xlarge":  {OnDemandUsdPerHour: 0.476, VcpuCount: 8, MemGb: 32},
	"m5n.4xlarge":  {OnDemandUsdPerHour: 0.952, VcpuCount: 16, MemGb: 64},
	"m5n.8xlarge":  {OnDemandUsdPerHour: 1.904, VcpuCount: 32, MemGb: 128},
	"m5n.12xlarge": {OnDemandUsdPerHour: 2.856, VcpuCount: 48, MemGb: 192},
	"m5n.16xlarge": {OnDemandUsdPerHour: 3.808, VcpuCount: 64, MemGb: 256},
	"m5n.24xlarge": {OnDemandUsdPerHour: 5.712, VcpuCount: 96, MemGb: 384},
	"m5n.metal":    {OnDemandUsdPerHour: 5.712, VcpuCount: 96, MemGb: 384},

	// CPU general: m6i
	"m6i.large":    {OnDemandUsdPerHour: 0.096, VcpuCount: 2, MemGb: 8},
	"m6i.xlarge":   {OnDemandUsdPerHour: 0.192, VcpuCount: 4, MemGb: 16},
	"m6i.2xlarge":  {OnDemandUsdPerHour: 0.384, VcpuCount: 8, MemGb: 32},
	"m6i.4xlarge":  {OnDemandUsdPerHour: 0.768, VcpuCount: 16, MemGb: 64},
	"m6i.8xlarge":  {OnDemandUsdPerHour: 1.536, VcpuCount: 32, MemGb: 128},
	"m6i.12xlarge": {OnDemandUsdPerHour: 2.304, VcpuCount: 48, MemGb: 192},
	"m6i.16xlarge": {OnDemandUsdPerHour: 3.072, VcpuCount: 64, MemGb: 256},
	"m6i.24xlarge": {OnDemandUsdPerHour: 4.608, VcpuCount: 96, MemGb: 384},
	"m6i.32xlarge": {OnDemandUsdPerHour: 6.144, VcpuCount: 128, MemGb: 512},

	// CPU general: m6a
	"m6a.large":    {OnDemandUsdPerHour: 0.0864, VcpuCount: 2, MemGb: 8},
	"m6a.xlarge":   {OnDemandUsdPerHour: 0.1728, VcpuCount: 4, MemGb: 16},
	"m6a.2xlarge":  {OnDemandUsdPerHour: 0.3456, VcpuCount: 8, MemGb: 32},
	"m6a.4xlarge":  {OnDemandUsdPerHour: 0.6912, VcpuCount: 16, MemGb: 64},
	"m6a.8xlarge":  {OnDemandUsdPerHour: 1.3824, VcpuCount: 32, MemGb: 128},
	"m6a.12xlarge": {OnDemandUsdPerHour: 2.0736, VcpuCount: 48, MemGb: 192},
	"m6a.16xlarge": {OnDemandUsdPerHour: 2.7648, VcpuCount: 64, MemGb: 256},
	"m6a.24xlarge": {OnDemandUsdPerHour: 4.1472, VcpuCount: 96, MemGb: 384},
	"m6a.32xlarge": {OnDemandUsdPerHour: 5.5296, VcpuCount: 128, MemGb: 512},
	"m6a.48xlarge": {OnDemandUsdPerHour: 8.2944, VcpuCount: 192, MemGb: 768},

	// CPU general: m6in (network-optimized)
	"m6in.large":    {OnDemandUsdPerHour: 0.13923, VcpuCount: 2, MemGb: 8},
	"m6in.xlarge":   {OnDemandUsdPerHour: 0.27846, VcpuCount: 4, MemGb: 16},
	"m6in.2xlarge":  {OnDemandUsdPerHour: 0.55692, VcpuCount: 8, MemGb: 32},
	"m6in.4xlarge":  {OnDemandUsdPerHour: 1.11384, VcpuCount: 16, MemGb: 64},
	"m6in.8xlarge":  {OnDemandUsdPerHour: 2.22768, VcpuCount: 32, MemGb: 128},
	"m6in.12xlarge": {OnDemandUsdPerHour: 3.34152, VcpuCount: 48, MemGb: 192},
	"m6in.16xlarge": {OnDemandUsdPerHour: 4.45536, VcpuCount: 64, MemGb: 256},
	"m6in.24xlarge": {OnDemandUsdPerHour: 6.68304, VcpuCount: 96, MemGb: 384},
	"m6in.32xlarge": {OnDemandUsdPerHour: 8.91072, VcpuCount: 128, MemGb: 512},
	"m6in.metal":    {OnDemandUsdPerHour: 8.91072, VcpuCount: 128, MemGb: 512},

	// CPU general: m7i
	"m7i.large":    {OnDemandUsdPerHour: 0.1008, VcpuCount: 2, MemGb: 8},
	"m7i.xlarge":   {OnDemandUsdPerHour: 0.2016, VcpuCount: 4, MemGb: 16},
	"m7i.2xlarge":  {OnDemandUsdPerHour: 0.4032, VcpuCount: 8, MemGb: 32},
	"m7i.4xlarge":  {OnDemandUsdPerHour: 0.8064, VcpuCount: 16, MemGb: 64},
	"m7i.8xlarge":  {OnDemandUsdPerHour: 1.6128, VcpuCount: 32, MemGb: 128},
	"m7i.12xlarge": {OnDemandUsdPerHour: 2.4192, VcpuCount: 48, MemGb: 192},
	"m7i.16xlarge": {OnDemandUsdPerHour: 3.2256, VcpuCount: 64, MemGb: 256},
	"m7i.24xlarge": {OnDemandUsdPerHour: 4.8384, VcpuCount: 96, MemGb: 384},
	"m7i.48xlarge": {OnDemandUsdPerHour: 9.6768, VcpuCount: 192, MemGb: 768},

	// CPU general: m7a
	"m7a.medium":   {OnDemandUsdPerHour: 0.05796, VcpuCount: 1, MemGb: 4},
	"m7a.large":    {OnDemandUsdPerHour: 0.11592, VcpuCount: 2, MemGb: 8},
	"m7a.xlarge":   {OnDemandUsdPerHour: 0.23184, VcpuCount: 4, MemGb: 16},
	"m7a.2xlarge":  {OnDemandUsdPerHour: 0.46368, VcpuCount: 8, MemGb: 32},
	"m7a.4xlarge":  {OnDemandUsdPerHour: 0.92736, VcpuCount: 16, MemGb: 64},
	"m7a.8xlarge":  {OnDemandUsdPerHour: 1.85472, VcpuCount: 32, MemGb: 128},
	"m7a.12xlarge": {OnDemandUsdPerHour: 2.78208, VcpuCount: 48, MemGb: 192},
	"m7a.16xlarge": {OnDemandUsdPerHour: 3.70944, VcpuCount: 64, MemGb: 256},
	"m7a.24xlarge": {OnDemandUsdPerHour: 5.56416, VcpuCount: 96, MemGb: 384},
	"m7a.32xlarge": {OnDemandUsdPerHour: 7.41888, VcpuCount: 128, MemGb: 512},
	"m7a.48xlarge": {OnDemandUsdPerHour: 11.12832, VcpuCount: 192, MemGb: 768},

	// CPU general: m6g (Graviton2)
	"m6g.medium":   {OnDemandUsdPerHour: 0.0385, VcpuCount: 1, MemGb: 4},
	"m6g.large":    {OnDemandUsdPerHour: 0.077, VcpuCount: 2, MemGb: 8},
	"m6g.xlarge":   {OnDemandUsdPerHour: 0.154, VcpuCount: 4, MemGb: 16},
	"m6g.2xlarge":  {OnDemandUsdPerHour: 0.308, VcpuCount: 8, MemGb: 32},
	"m6g.4xlarge":  {OnDemandUsdPerHour: 0.616, VcpuCount: 16, MemGb: 64},
	"m6g.8xlarge":  {OnDemandUsdPerHour: 1.232, VcpuCount: 32, MemGb: 128},
	"m6g.12xlarge": {OnDemandUsdPerHour: 1.848, VcpuCount: 48, MemGb: 192},
	"m6g.16xlarge": {OnDemandUsdPerHour: 2.464, VcpuCount: 64, MemGb: 256},
	"m6g.metal":    {OnDemandUsdPerHour: 2.464, VcpuCount: 64, MemGb: 256},

	// CPU general: m7g (Graviton3)
	"m7g.medium":   {OnDemandUsdPerHour: 0.0408, VcpuCount: 1, MemGb: 4},
	"m7g.large":    {OnDemandUsdPerHour: 0.0816, VcpuCount: 2, MemGb: 8},
	"m7g.xlarge":   {OnDemandUsdPerHour: 0.1632, VcpuCount: 4, MemGb: 16},
	"m7g.2xlarge":  {OnDemandUsdPerHour: 0.3264, VcpuCount: 8, MemGb: 32},
	"m7g.4xlarge":  {OnDemandUsdPerHour: 0.6528, VcpuCount: 16, MemGb: 64},
	"m7g.8xlarge":  {OnDemandUsdPerHour: 1.3056, VcpuCount: 32, MemGb: 128},
	"m7g.12xlarge": {OnDemandUsdPerHour: 1.9584, VcpuCount: 48, MemGb: 192},
	"m7g.16xlarge": {OnDemandUsdPerHour: 2.6112, VcpuCount: 64, MemGb: 256},
	"m7g.metal":    {OnDemandUsdPerHour: 2.6112, VcpuCount: 64, MemGb: 256},

	// CPU general: m8g (Graviton4)
	"m8g.medium":   {OnDemandUsdPerHour: 0.04488, VcpuCount: 1, MemGb: 4},
	"m8g.large":    {OnDemandUsdPerHour: 0.08976, VcpuCount: 2, MemGb: 8},
	"m8g.xlarge":   {OnDemandUsdPerHour: 0.17952, VcpuCount: 4, MemGb: 16},
	"m8g.2xlarge":  {OnDemandUsdPerHour: 0.35904, VcpuCount: 8, MemGb: 32},
	"m8g.4xlarge":  {OnDemandUsdPerHour: 0.71808, VcpuCount: 16, MemGb: 64},
	"m8g.8xlarge":  {OnDemandUsdPerHour: 1.43616, VcpuCount: 32, MemGb: 128},
	"m8g.12xlarge": {OnDemandUsdPerHour: 2.15424, VcpuCount: 48, MemGb: 192},
	"m8g.16xlarge": {OnDemandUsdPerHour: 2.87232, VcpuCount: 64, MemGb: 256},
	"m8g.24xlarge": {OnDemandUsdPerHour: 4.30848, VcpuCount: 96, MemGb: 384},
	"m8g.48xlarge": {OnDemandUsdPerHour: 8.61696, VcpuCount: 192, MemGb: 768},

	// CPU compute: c5
	"c5.large":    {OnDemandUsdPerHour: 0.085, VcpuCount: 2, MemGb: 4},
	"c5.xlarge":   {OnDemandUsdPerHour: 0.17, VcpuCount: 4, MemGb: 8},
	"c5.2xlarge":  {OnDemandUsdPerHour: 0.34, VcpuCount: 8, MemGb: 16},
	"c5.4xlarge":  {OnDemandUsdPerHour: 0.68, VcpuCount: 16, MemGb: 32},
	"c5.9xlarge":  {OnDemandUsdPerHour: 1.53, VcpuCount: 36, MemGb: 72},
	"c5.12xlarge": {OnDemandUsdPerHour: 2.04, VcpuCount: 48, MemGb: 96},
	"c5.18xlarge": {OnDemandUsdPerHour: 3.06, VcpuCount: 72, MemGb: 144},
	"c5.24xlarge": {OnDemandUsdPerHour: 4.08, VcpuCount: 96, MemGb: 192},

	// CPU compute: c5a (AMD-EPYC)
	"c5a.large":    {OnDemandUsdPerHour: 0.077, VcpuCount: 2, MemGb: 4},
	"c5a.xlarge":   {OnDemandUsdPerHour: 0.154, VcpuCount: 4, MemGb: 8},
	"c5a.2xlarge":  {OnDemandUsdPerHour: 0.308, VcpuCount: 8, MemGb: 16},
	"c5a.4xlarge":  {OnDemandUsdPerHour: 0.616, VcpuCount: 16, MemGb: 32},
	"c5a.8xlarge":  {OnDemandUsdPerHour: 1.232, VcpuCount: 32, MemGb: 64},
	"c5a.12xlarge": {OnDemandUsdPerHour: 1.848, VcpuCount: 48, MemGb: 96},
	"c5a.16xlarge": {OnDemandUsdPerHour: 2.464, VcpuCount: 64, MemGb: 128},
	"c5a.24xlarge": {OnDemandUsdPerHour: 3.696, VcpuCount: 96, MemGb: 192},

	// CPU compute: c5n (network-optimized)
	"c5n.large":    {OnDemandUsdPerHour: 0.108, VcpuCount: 2, MemGb: 5.25},
	"c5n.xlarge":   {OnDemandUsdPerHour: 0.216, VcpuCount: 4, MemGb: 10.5},
	"c5n.2xlarge":  {OnDemandUsdPerHour: 0.432, VcpuCount: 8, MemGb: 21},
	"c5n.4xlarge":  {OnDemandUsdPerHour: 0.864, VcpuCount: 16, MemGb: 42},
	"c5n.9xlarge":  {OnDemandUsdPerHour: 1.944, VcpuCount: 36, MemGb: 96},
	"c5n.18xlarge": {OnDemandUsdPerHour: 3.888, VcpuCount: 72, MemGb: 192},
	"c5n.metal":    {OnDemandUsdPerHour: 3.888, VcpuCount: 72, MemGb: 192},

	// CPU compute: c6i
	"c6i.large":    {OnDemandUsdPerHour: 0.085, VcpuCount: 2, MemGb: 4},
	"c6i.xlarge":   {OnDemandUsdPerHour: 0.17, VcpuCount: 4, MemGb: 8},
	"c6i.2xlarge":  {OnDemandUsdPerHour: 0.34, VcpuCount: 8, MemGb: 16},
	"c6i.4xlarge":  {OnDemandUsdPerHour: 0.68, VcpuCount: 16, MemGb: 32},
	"c6i.8xlarge":  {OnDemandUsdPerHour: 1.36, VcpuCount: 32, MemGb: 64},
	"c6i.12xlarge": {OnDemandUsdPerHour: 2.04, VcpuCount: 48, MemGb: 96},
	"c6i.16xlarge": {OnDemandUsdPerHour: 2.72, VcpuCount: 64, MemGb: 128},
	"c6i.24xlarge": {OnDemandUsdPerHour: 4.08, VcpuCount: 96, MemGb: 192},
	"c6i.32xlarge": {OnDemandUsdPerHour: 5.44, VcpuCount: 128, MemGb: 256},

	// CPU compute: c6a (AMD-EPYC)
	"c6a.large":    {OnDemandUsdPerHour: 0.0765, VcpuCount: 2, MemGb: 4},
	"c6a.xlarge":   {OnDemandUsdPerHour: 0.153, VcpuCount: 4, MemGb: 8},
	"c6a.2xlarge":  {OnDemandUsdPerHour: 0.306, VcpuCount: 8, MemGb: 16},
	"c6a.4xlarge":  {OnDemandUsdPerHour: 0.612, VcpuCount: 16, MemGb: 32},
	"c6a.8xlarge":  {OnDemandUsdPerHour: 1.224, VcpuCount: 32, MemGb: 64},
	"c6a.12xlarge": {OnDemandUsdPerHour: 1.836, VcpuCount: 48, MemGb: 96},
	"c6a.16xlarge": {OnDemandUsdPerHour: 2.448, VcpuCount: 64, MemGb: 128},
	"c6a.24xlarge": {OnDemandUsdPerHour: 3.672, VcpuCount: 96, MemGb: 192},
	"c6a.32xlarge": {OnDemandUsdPerHour: 4.896, VcpuCount: 128, MemGb: 256},
	"c6a.48xlarge": {OnDemandUsdPerHour: 7.344, VcpuCount: 192, MemGb: 384},
	"c6a.metal":    {OnDemandUsdPerHour: 7.344, VcpuCount: 192, MemGb: 384},

	// CPU compute: c6in (network-optimized)
	"c6in.large":    {OnDemandUsdPerHour: 0.1134, VcpuCount: 2, MemGb: 4},
	"c6in.xlarge":   {OnDemandUsdPerHour: 0.2268, VcpuCount: 4, MemGb: 8},
	"c6in.2xlarge":  {OnDemandUsdPerHour: 0.4536, VcpuCount: 8, MemGb: 16},
	"c6in.4xlarge":  {OnDemandUsdPerHour: 0.9072, VcpuCount: 16, MemGb: 32},
	"c6in.8xlarge":  {OnDemandUsdPerHour: 1.8144, VcpuCount: 32, MemGb: 64},
	"c6in.12xlarge": {OnDemandUsdPerHour: 2.7216, VcpuCount: 48, MemGb: 96},
	"c6in.16xlarge": {OnDemandUsdPerHour: 3.6288, VcpuCount: 64, MemGb: 128},
	"c6in.24xlarge": {OnDemandUsdPerHour: 5.4432, VcpuCount: 96, MemGb: 192},
	"c6in.32xlarge": {OnDemandUsdPerHour: 7.2576, VcpuCount: 128, MemGb: 256},
	"c6in.metal":    {OnDemandUsdPerHour: 7.2576, VcpuCount: 128, MemGb: 256},

	// CPU compute: c7i
	"c7i.large":    {OnDemandUsdPerHour: 0.08925, VcpuCount: 2, MemGb: 4},
	"c7i.xlarge":   {OnDemandUsdPerHour: 0.1785, VcpuCount: 4, MemGb: 8},
	"c7i.2xlarge":  {OnDemandUsdPerHour: 0.357, VcpuCount: 8, MemGb: 16},
	"c7i.4xlarge":  {OnDemandUsdPerHour: 0.714, VcpuCount: 16, MemGb: 32},
	"c7i.8xlarge":  {OnDemandUsdPerHour: 1.428, VcpuCount: 32, MemGb: 64},
	"c7i.12xlarge": {OnDemandUsdPerHour: 2.142, VcpuCount: 48, MemGb: 96},
	"c7i.16xlarge": {OnDemandUsdPerHour: 2.856, VcpuCount: 64, MemGb: 128},
	"c7i.24xlarge": {OnDemandUsdPerHour: 4.284, VcpuCount: 96, MemGb: 192},
	"c7i.48xlarge": {OnDemandUsdPerHour: 8.568, VcpuCount: 192, MemGb: 384},

	// CPU compute: c7a
	"c7a.medium":   {OnDemandUsdPerHour: 0.05132, VcpuCount: 1, MemGb: 2},
	"c7a.large":    {OnDemandUsdPerHour: 0.10264, VcpuCount: 2, MemGb: 4},
	"c7a.xlarge":   {OnDemandUsdPerHour: 0.20528, VcpuCount: 4, MemGb: 8},
	"c7a.2xlarge":  {OnDemandUsdPerHour: 0.41056, VcpuCount: 8, MemGb: 16},
	"c7a.4xlarge":  {OnDemandUsdPerHour: 0.82112, VcpuCount: 16, MemGb: 32},
	"c7a.8xlarge":  {OnDemandUsdPerHour: 1.64224, VcpuCount: 32, MemGb: 64},
	"c7a.12xlarge": {OnDemandUsdPerHour: 2.46336, VcpuCount: 48, MemGb: 96},
	"c7a.16xlarge": {OnDemandUsdPerHour: 3.28448, VcpuCount: 64, MemGb: 128},
	"c7a.24xlarge": {OnDemandUsdPerHour: 4.92672, VcpuCount: 96, MemGb: 192},
	"c7a.32xlarge": {OnDemandUsdPerHour: 6.56896, VcpuCount: 128, MemGb: 256},
	"c7a.48xlarge": {OnDemandUsdPerHour: 9.85344, VcpuCount: 192, MemGb: 384},

	// CPU compute: c6g (Graviton2)
	"c6g.medium":   {OnDemandUsdPerHour: 0.034, VcpuCount: 1, MemGb: 2},
	"c6g.large":    {OnDemandUsdPerHour: 0.068, VcpuCount: 2, MemGb: 4},
	"c6g.xlarge":   {OnDemandUsdPerHour: 0.136, VcpuCount: 4, MemGb: 8},
	"c6g.2xlarge":  {OnDemandUsdPerHour: 0.272, VcpuCount: 8, MemGb: 16},
	"c6g.4xlarge":  {OnDemandUsdPerHour: 0.544, VcpuCount: 16, MemGb: 32},
	"c6g.8xlarge":  {OnDemandUsdPerHour: 1.088, VcpuCount: 32, MemGb: 64},
	"c6g.12xlarge": {OnDemandUsdPerHour: 1.632, VcpuCount: 48, MemGb: 96},
	"c6g.16xlarge": {OnDemandUsdPerHour: 2.176, VcpuCount: 64, MemGb: 128},
	"c6g.metal":    {OnDemandUsdPerHour: 2.176, VcpuCount: 64, MemGb: 128},

	// CPU compute: c7g (Graviton3)
	"c7g.medium":   {OnDemandUsdPerHour: 0.0363, VcpuCount: 1, MemGb: 2},
	"c7g.large":    {OnDemandUsdPerHour: 0.0725, VcpuCount: 2, MemGb: 4},
	"c7g.xlarge":   {OnDemandUsdPerHour: 0.145, VcpuCount: 4, MemGb: 8},
	"c7g.2xlarge":  {OnDemandUsdPerHour: 0.29, VcpuCount: 8, MemGb: 16},
	"c7g.4xlarge":  {OnDemandUsdPerHour: 0.58, VcpuCount: 16, MemGb: 32},
	"c7g.8xlarge":  {OnDemandUsdPerHour: 1.16, VcpuCount: 32, MemGb: 64},
	"c7g.12xlarge": {OnDemandUsdPerHour: 1.74, VcpuCount: 48, MemGb: 96},
	"c7g.16xlarge": {OnDemandUsdPerHour: 2.32, VcpuCount: 64, MemGb: 128},
	"c7g.metal":    {OnDemandUsdPerHour: 2.32, VcpuCount: 64, MemGb: 128},

	// CPU compute: c8g (Graviton4)
	"c8g.medium":   {OnDemandUsdPerHour: 0.03988, VcpuCount: 1, MemGb: 2},
	"c8g.large":    {OnDemandUsdPerHour: 0.07976, VcpuCount: 2, MemGb: 4},
	"c8g.xlarge":   {OnDemandUsdPerHour: 0.15952, VcpuCount: 4, MemGb: 8},
	"c8g.2xlarge":  {OnDemandUsdPerHour: 0.31904, VcpuCount: 8, MemGb: 16},
	"c8g.4xlarge":  {OnDemandUsdPerHour: 0.63808, VcpuCount: 16, MemGb: 32},
	"c8g.8xlarge":  {OnDemandUsdPerHour: 1.27616, VcpuCount: 32, MemGb: 64},
	"c8g.12xlarge": {OnDemandUsdPerHour: 1.91424, VcpuCount: 48, MemGb: 96},
	"c8g.16xlarge": {OnDemandUsdPerHour: 2.55232, VcpuCount: 64, MemGb: 128},
	"c8g.24xlarge": {OnDemandUsdPerHour: 3.82848, VcpuCount: 96, MemGb: 192},
	"c8g.48xlarge": {OnDemandUsdPerHour: 7.65696, VcpuCount: 192, MemGb: 384},

	// CPU memory: r5
	"r5.large":    {OnDemandUsdPerHour: 0.126, VcpuCount: 2, MemGb: 16},
	"r5.xlarge":   {OnDemandUsdPerHour: 0.252, VcpuCount: 4, MemGb: 32},
	"r5.2xlarge":  {OnDemandUsdPerHour: 0.504, VcpuCount: 8, MemGb: 64},
	"r5.4xlarge":  {OnDemandUsdPerHour: 1.008, VcpuCount: 16, MemGb: 128},
	"r5.8xlarge":  {OnDemandUsdPerHour: 2.016, VcpuCount: 32, MemGb: 256},
	"r5.12xlarge": {OnDemandUsdPerHour: 3.024, VcpuCount: 48, MemGb: 384},
	"r5.16xlarge": {OnDemandUsdPerHour: 4.032, VcpuCount: 64, MemGb: 512},
	"r5.24xlarge": {OnDemandUsdPerHour: 6.048, VcpuCount: 96, MemGb: 768},

	// CPU memory: r5a (AMD-EPYC)
	"r5a.large":    {OnDemandUsdPerHour: 0.113, VcpuCount: 2, MemGb: 16},
	"r5a.xlarge":   {OnDemandUsdPerHour: 0.226, VcpuCount: 4, MemGb: 32},
	"r5a.2xlarge":  {OnDemandUsdPerHour: 0.452, VcpuCount: 8, MemGb: 64},
	"r5a.4xlarge":  {OnDemandUsdPerHour: 0.904, VcpuCount: 16, MemGb: 128},
	"r5a.8xlarge":  {OnDemandUsdPerHour: 1.808, VcpuCount: 32, MemGb: 256},
	"r5a.12xlarge": {OnDemandUsdPerHour: 2.712, VcpuCount: 48, MemGb: 384},
	"r5a.16xlarge": {OnDemandUsdPerHour: 3.616, VcpuCount: 64, MemGb: 512},
	"r5a.24xlarge": {OnDemandUsdPerHour: 5.424, VcpuCount: 96, MemGb: 768},

	// CPU memory: r5n (network-optimized)
	"r5n.large":    {OnDemandUsdPerHour: 0.149, VcpuCount: 2, MemGb: 16},
	"r5n.xlarge":   {OnDemandUsdPerHour: 0.298, VcpuCount: 4, MemGb: 32},
	"r5n.2xlarge":  {OnDemandUsdPerHour: 0.596, VcpuCount: 8, MemGb: 64},
	"r5n.4xlarge":  {OnDemandUsdPerHour: 1.192, VcpuCount: 16, MemGb: 128},
	"r5n.8xlarge":  {OnDemandUsdPerHour: 2.384, VcpuCount: 32, MemGb: 256},
	"r5n.12xlarge": {OnDemandUsdPerHour: 3.576, VcpuCount: 48, MemGb: 384},
	"r5n.16xlarge": {OnDemandUsdPerHour: 4.768, VcpuCount: 64, MemGb: 512},
	"r5n.24xlarge": {OnDemandUsdPerHour: 7.152, VcpuCount: 96, MemGb: 768},
	"r5n.metal":    {OnDemandUsdPerHour: 7.152, VcpuCount: 96, MemGb: 768},

	// CPU memory: r6i
	"r6i.large":    {OnDemandUsdPerHour: 0.126, VcpuCount: 2, MemGb: 16},
	"r6i.xlarge":   {OnDemandUsdPerHour: 0.252, VcpuCount: 4, MemGb: 32},
	"r6i.2xlarge":  {OnDemandUsdPerHour: 0.504, VcpuCount: 8, MemGb: 64},
	"r6i.4xlarge":  {OnDemandUsdPerHour: 1.008, VcpuCount: 16, MemGb: 128},
	"r6i.8xlarge":  {OnDemandUsdPerHour: 2.016, VcpuCount: 32, MemGb: 256},
	"r6i.12xlarge": {OnDemandUsdPerHour: 3.024, VcpuCount: 48, MemGb: 384},
	"r6i.16xlarge": {OnDemandUsdPerHour: 4.032, VcpuCount: 64, MemGb: 512},
	"r6i.24xlarge": {OnDemandUsdPerHour: 6.048, VcpuCount: 96, MemGb: 768},
	"r6i.32xlarge": {OnDemandUsdPerHour: 8.064, VcpuCount: 128, MemGb: 1024},

	// CPU memory: r6a (AMD-EPYC)
	"r6a.large":    {OnDemandUsdPerHour: 0.1134, VcpuCount: 2, MemGb: 16},
	"r6a.xlarge":   {OnDemandUsdPerHour: 0.2268, VcpuCount: 4, MemGb: 32},
	"r6a.2xlarge":  {OnDemandUsdPerHour: 0.4536, VcpuCount: 8, MemGb: 64},
	"r6a.4xlarge":  {OnDemandUsdPerHour: 0.9072, VcpuCount: 16, MemGb: 128},
	"r6a.8xlarge":  {OnDemandUsdPerHour: 1.8144, VcpuCount: 32, MemGb: 256},
	"r6a.12xlarge": {OnDemandUsdPerHour: 2.7216, VcpuCount: 48, MemGb: 384},
	"r6a.16xlarge": {OnDemandUsdPerHour: 3.6288, VcpuCount: 64, MemGb: 512},
	"r6a.24xlarge": {OnDemandUsdPerHour: 5.4432, VcpuCount: 96, MemGb: 768},
	"r6a.32xlarge": {OnDemandUsdPerHour: 7.2576, VcpuCount: 128, MemGb: 1024},
	"r6a.48xlarge": {OnDemandUsdPerHour: 10.8864, VcpuCount: 192, MemGb: 1536},
	"r6a.metal":    {OnDemandUsdPerHour: 10.8864, VcpuCount: 192, MemGb: 1536},

	// CPU memory: r6in (network-optimized)
	"r6in.large":    {OnDemandUsdPerHour: 0.17433, VcpuCount: 2, MemGb: 16},
	"r6in.xlarge":   {OnDemandUsdPerHour: 0.34866, VcpuCount: 4, MemGb: 32},
	"r6in.2xlarge":  {OnDemandUsdPerHour: 0.69732, VcpuCount: 8, MemGb: 64},
	"r6in.4xlarge":  {OnDemandUsdPerHour: 1.39464, VcpuCount: 16, MemGb: 128},
	"r6in.8xlarge":  {OnDemandUsdPerHour: 2.78928, VcpuCount: 32, MemGb: 256},
	"r6in.12xlarge": {OnDemandUsdPerHour: 4.18392, VcpuCount: 48, MemGb: 384},
	"r6in.16xlarge": {OnDemandUsdPerHour: 5.57856, VcpuCount: 64, MemGb: 512},
	"r6in.24xlarge": {OnDemandUsdPerHour: 8.36784, VcpuCount: 96, MemGb: 768},
	"r6in.32xlarge": {OnDemandUsdPerHour: 11.15712, VcpuCount: 128, MemGb: 1024},
	"r6in.metal":    {OnDemandUsdPerHour: 11.15712, VcpuCount: 128, MemGb: 1024},

	// CPU memory: r7i
	"r7i.large":    {OnDemandUsdPerHour: 0.1323, VcpuCount: 2, MemGb: 16},
	"r7i.xlarge":   {OnDemandUsdPerHour: 0.2646, VcpuCount: 4, MemGb: 32},
	"r7i.2xlarge":  {OnDemandUsdPerHour: 0.5292, VcpuCount: 8, MemGb: 64},
	"r7i.4xlarge":  {OnDemandUsdPerHour: 1.0584, VcpuCount: 16, MemGb: 128},
	"r7i.8xlarge":  {OnDemandUsdPerHour: 2.1168, VcpuCount: 32, MemGb: 256},
	"r7i.12xlarge": {OnDemandUsdPerHour: 3.1752, VcpuCount: 48, MemGb: 384},
	"r7i.16xlarge": {OnDemandUsdPerHour: 4.2336, VcpuCount: 64, MemGb: 512},
	"r7i.24xlarge": {OnDemandUsdPerHour: 6.3504, VcpuCount: 96, MemGb: 768},
	"r7i.48xlarge": {OnDemandUsdPerHour: 12.7008, VcpuCount: 192, MemGb: 1536},

	// CPU memory: r7a
	"r7a.medium":   {OnDemandUsdPerHour: 0.07608, VcpuCount: 1, MemGb: 8},
	"r7a.large":    {OnDemandUsdPerHour: 0.15215, VcpuCount: 2, MemGb: 16},
	"r7a.xlarge":   {OnDemandUsdPerHour: 0.3043, VcpuCount: 4, MemGb: 32},
	"r7a.2xlarge":  {OnDemandUsdPerHour: 0.6086, VcpuCount: 8, MemGb: 64},
	"r7a.4xlarge":  {OnDemandUsdPerHour: 1.2172, VcpuCount: 16, MemGb: 128},
	"r7a.8xlarge":  {OnDemandUsdPerHour: 2.4344, VcpuCount: 32, MemGb: 256},
	"r7a.12xlarge": {OnDemandUsdPerHour: 3.6516, VcpuCount: 48, MemGb: 384},
	"r7a.16xlarge": {OnDemandUsdPerHour: 4.8688, VcpuCount: 64, MemGb: 512},
	"r7a.24xlarge": {OnDemandUsdPerHour: 7.3032, VcpuCount: 96, MemGb: 768},
	"r7a.32xlarge": {OnDemandUsdPerHour: 9.7376, VcpuCount: 128, MemGb: 1024},
	"r7a.48xlarge": {OnDemandUsdPerHour: 14.6064, VcpuCount: 192, MemGb: 1536},

	// CPU memory: r6g (Graviton2)
	"r6g.medium":   {OnDemandUsdPerHour: 0.0504, VcpuCount: 1, MemGb: 8},
	"r6g.large":    {OnDemandUsdPerHour: 0.1008, VcpuCount: 2, MemGb: 16},
	"r6g.xlarge":   {OnDemandUsdPerHour: 0.2016, VcpuCount: 4, MemGb: 32},
	"r6g.2xlarge":  {OnDemandUsdPerHour: 0.4032, VcpuCount: 8, MemGb: 64},
	"r6g.4xlarge":  {OnDemandUsdPerHour: 0.8064, VcpuCount: 16, MemGb: 128},
	"r6g.8xlarge":  {OnDemandUsdPerHour: 1.6128, VcpuCount: 32, MemGb: 256},
	"r6g.12xlarge": {OnDemandUsdPerHour: 2.4192, VcpuCount: 48, MemGb: 384},
	"r6g.16xlarge": {OnDemandUsdPerHour: 3.2256, VcpuCount: 64, MemGb: 512},
	"r6g.metal":    {OnDemandUsdPerHour: 3.2256, VcpuCount: 64, MemGb: 512},

	// CPU memory: r7g (Graviton3)
	"r7g.medium":   {OnDemandUsdPerHour: 0.0536, VcpuCount: 1, MemGb: 8},
	"r7g.large":    {OnDemandUsdPerHour: 0.1071, VcpuCount: 2, MemGb: 16},
	"r7g.xlarge":   {OnDemandUsdPerHour: 0.2142, VcpuCount: 4, MemGb: 32},
	"r7g.2xlarge":  {OnDemandUsdPerHour: 0.4284, VcpuCount: 8, MemGb: 64},
	"r7g.4xlarge":  {OnDemandUsdPerHour: 0.8568, VcpuCount: 16, MemGb: 128},
	"r7g.8xlarge":  {OnDemandUsdPerHour: 1.7136, VcpuCount: 32, MemGb: 256},
	"r7g.12xlarge": {OnDemandUsdPerHour: 2.5704, VcpuCount: 48, MemGb: 384},
	"r7g.16xlarge": {OnDemandUsdPerHour: 3.4272, VcpuCount: 64, MemGb: 512},
	"r7g.metal":    {OnDemandUsdPerHour: 3.4272, VcpuCount: 64, MemGb: 512},

	// CPU memory: r8g (Graviton4)
	"r8g.medium":   {OnDemandUsdPerHour: 0.05891, VcpuCount: 1, MemGb: 8},
	"r8g.large":    {OnDemandUsdPerHour: 0.11782, VcpuCount: 2, MemGb: 16},
	"r8g.xlarge":   {OnDemandUsdPerHour: 0.23564, VcpuCount: 4, MemGb: 32},
	"r8g.2xlarge":  {OnDemandUsdPerHour: 0.47128, VcpuCount: 8, MemGb: 64},
	"r8g.4xlarge":  {OnDemandUsdPerHour: 0.94256, VcpuCount: 16, MemGb: 128},
	"r8g.8xlarge":  {OnDemandUsdPerHour: 1.88512, VcpuCount: 32, MemGb: 256},
	"r8g.12xlarge": {OnDemandUsdPerHour: 2.82768, VcpuCount: 48, MemGb: 384},
	"r8g.16xlarge": {OnDemandUsdPerHour: 3.77024, VcpuCount: 64, MemGb: 512},
	"r8g.24xlarge": {OnDemandUsdPerHour: 5.65536, VcpuCount: 96, MemGb: 768},
	"r8g.48xlarge": {OnDemandUsdPerHour: 11.31072, VcpuCount: 192, MemGb: 1536},

	// CPU memory: x2idn (Intel high-memory)
	"x2idn.16xlarge": {OnDemandUsdPerHour: 6.669, VcpuCount: 64, MemGb: 1024},
	"x2idn.24xlarge": {OnDemandUsdPerHour: 10.0035, VcpuCount: 96, MemGb: 1536},
	"x2idn.32xlarge": {OnDemandUsdPerHour: 13.338, VcpuCount: 128, MemGb: 2048},
	"x2idn.metal":    {OnDemandUsdPerHour: 13.338, VcpuCount: 128, MemGb: 2048},

	// CPU memory: x2iedn (Intel high-memory, extended)
	"x2iedn.xlarge":   {OnDemandUsdPerHour: 0.83363, VcpuCount: 4, MemGb: 128},
	"x2iedn.2xlarge":  {OnDemandUsdPerHour: 1.66725, VcpuCount: 8, MemGb: 256},
	"x2iedn.4xlarge":  {OnDemandUsdPerHour: 3.3345, VcpuCount: 16, MemGb: 512},
	"x2iedn.8xlarge":  {OnDemandUsdPerHour: 6.669, VcpuCount: 32, MemGb: 1024},
	"x2iedn.16xlarge": {OnDemandUsdPerHour: 13.338, VcpuCount: 64, MemGb: 2048},
	"x2iedn.24xlarge": {OnDemandUsdPerHour: 20.007, VcpuCount: 96, MemGb: 3072},
	"x2iedn.32xlarge": {OnDemandUsdPerHour: 26.676, VcpuCount: 128, MemGb: 4096},
	"x2iedn.metal":    {OnDemandUsdPerHour: 26.676, VcpuCount: 128, MemGb: 4096},

	// CPU memory: x2gd (Graviton2 high-memory)
	"x2gd.medium":   {OnDemandUsdPerHour: 0.0835, VcpuCount: 1, MemGb: 16},
	"x2gd.large":    {OnDemandUsdPerHour: 0.167, VcpuCount: 2, MemGb: 32},
	"x2gd.xlarge":   {OnDemandUsdPerHour: 0.334, VcpuCount: 4, MemGb: 64},
	"x2gd.2xlarge":  {OnDemandUsdPerHour: 0.668, VcpuCount: 8, MemGb: 128},
	"x2gd.4xlarge":  {OnDemandUsdPerHour: 1.336, VcpuCount: 16, MemGb: 256},
	"x2gd.8xlarge":  {OnDemandUsdPerHour: 2.672, VcpuCount: 32, MemGb: 512},
	"x2gd.12xlarge": {OnDemandUsdPerHour: 4.008, VcpuCount: 48, MemGb: 768},
	"x2gd.16xlarge": {OnDemandUsdPerHour: 5.344, VcpuCount: 64, MemGb: 1024},
	"x2gd.metal":    {OnDemandUsdPerHour: 5.344, VcpuCount: 64, MemGb: 1024},

	// CPU memory: z1d (high-frequency)
	"z1d.large":    {OnDemandUsdPerHour: 0.186, VcpuCount: 2, MemGb: 16},
	"z1d.xlarge":   {OnDemandUsdPerHour: 0.372, VcpuCount: 4, MemGb: 32},
	"z1d.2xlarge":  {OnDemandUsdPerHour: 0.744, VcpuCount: 8, MemGb: 64},
	"z1d.3xlarge":  {OnDemandUsdPerHour: 1.116, VcpuCount: 12, MemGb: 96},
	"z1d.6xlarge":  {OnDemandUsdPerHour: 2.232, VcpuCount: 24, MemGb: 192},
	"z1d.12xlarge": {OnDemandUsdPerHour: 4.464, VcpuCount: 48, MemGb: 384},
	"z1d.metal":    {OnDemandUsdPerHour: 4.464, VcpuCount: 48, MemGb: 384},

	// CPU general: t2 (legacy burstable, no Nitro)
	"t2.nano":    {OnDemandUsdPerHour: 0.0058, VcpuCount: 1, MemGb: 0.5},
	"t2.micro":   {OnDemandUsdPerHour: 0.0116, VcpuCount: 1, MemGb: 1},
	"t2.small":   {OnDemandUsdPerHour: 0.023, VcpuCount: 1, MemGb: 2},
	"t2.medium":  {OnDemandUsdPerHour: 0.0464, VcpuCount: 2, MemGb: 4},
	"t2.large":   {OnDemandUsdPerHour: 0.0928, VcpuCount: 2, MemGb: 8},
	"t2.xlarge":  {OnDemandUsdPerHour: 0.1856, VcpuCount: 4, MemGb: 16},
	"t2.2xlarge": {OnDemandUsdPerHour: 0.3712, VcpuCount: 8, MemGb: 32},

	// CPU general: t3 (Nitro burstable, AMD64)
	"t3.nano":    {OnDemandUsdPerHour: 0.0052, VcpuCount: 2, MemGb: 0.5},
	"t3.micro":   {OnDemandUsdPerHour: 0.0104, VcpuCount: 2, MemGb: 1},
	"t3.small":   {OnDemandUsdPerHour: 0.0208, VcpuCount: 2, MemGb: 2},
	"t3.medium":  {OnDemandUsdPerHour: 0.0416, VcpuCount: 2, MemGb: 4},
	"t3.large":   {OnDemandUsdPerHour: 0.0832, VcpuCount: 2, MemGb: 8},
	"t3.xlarge":  {OnDemandUsdPerHour: 0.1664, VcpuCount: 4, MemGb: 16},
	"t3.2xlarge": {OnDemandUsdPerHour: 0.3328, VcpuCount: 8, MemGb: 32},

	// CPU general: t3a (AMD-EPYC variant of t3)
	"t3a.nano":    {OnDemandUsdPerHour: 0.0047, VcpuCount: 2, MemGb: 0.5},
	"t3a.micro":   {OnDemandUsdPerHour: 0.0094, VcpuCount: 2, MemGb: 1},
	"t3a.small":   {OnDemandUsdPerHour: 0.0188, VcpuCount: 2, MemGb: 2},
	"t3a.medium":  {OnDemandUsdPerHour: 0.0376, VcpuCount: 2, MemGb: 4},
	"t3a.large":   {OnDemandUsdPerHour: 0.0752, VcpuCount: 2, MemGb: 8},
	"t3a.xlarge":  {OnDemandUsdPerHour: 0.1504, VcpuCount: 4, MemGb: 16},
	"t3a.2xlarge": {OnDemandUsdPerHour: 0.3008, VcpuCount: 8, MemGb: 32},

	// CPU general: t4g (Graviton2 burstable)
	"t4g.nano":    {OnDemandUsdPerHour: 0.0042, VcpuCount: 2, MemGb: 0.5},
	"t4g.micro":   {OnDemandUsdPerHour: 0.0084, VcpuCount: 2, MemGb: 1},
	"t4g.small":   {OnDemandUsdPerHour: 0.0168, VcpuCount: 2, MemGb: 2},
	"t4g.medium":  {OnDemandUsdPerHour: 0.0336, VcpuCount: 2, MemGb: 4},
	"t4g.large":   {OnDemandUsdPerHour: 0.0672, VcpuCount: 2, MemGb: 8},
	"t4g.xlarge":  {OnDemandUsdPerHour: 0.1344, VcpuCount: 4, MemGb: 16},
	"t4g.2xlarge": {OnDemandUsdPerHour: 0.2688, VcpuCount: 8, MemGb: 32},

	// Storage optimized: i3 (NVMe SSD)
	"i3.large":    {OnDemandUsdPerHour: 0.156, VcpuCount: 2, MemGb: 15.25},
	"i3.xlarge":   {OnDemandUsdPerHour: 0.312, VcpuCount: 4, MemGb: 30.5},
	"i3.2xlarge":  {OnDemandUsdPerHour: 0.624, VcpuCount: 8, MemGb: 61},
	"i3.4xlarge":  {OnDemandUsdPerHour: 1.248, VcpuCount: 16, MemGb: 122},
	"i3.8xlarge":  {OnDemandUsdPerHour: 2.496, VcpuCount: 32, MemGb: 244},
	"i3.16xlarge": {OnDemandUsdPerHour: 4.992, VcpuCount: 64, MemGb: 488},
	"i3.metal":    {OnDemandUsdPerHour: 4.992, VcpuCount: 64, MemGb: 488},

	// Storage optimized: i3en (dense NVMe SSD)
	"i3en.large":    {OnDemandUsdPerHour: 0.226, VcpuCount: 2, MemGb: 16},
	"i3en.xlarge":   {OnDemandUsdPerHour: 0.452, VcpuCount: 4, MemGb: 32},
	"i3en.2xlarge":  {OnDemandUsdPerHour: 0.904, VcpuCount: 8, MemGb: 64},
	"i3en.3xlarge":  {OnDemandUsdPerHour: 1.356, VcpuCount: 12, MemGb: 96},
	"i3en.6xlarge":  {OnDemandUsdPerHour: 2.712, VcpuCount: 24, MemGb: 192},
	"i3en.12xlarge": {OnDemandUsdPerHour: 5.424, VcpuCount: 48, MemGb: 384},
	"i3en.24xlarge": {OnDemandUsdPerHour: 10.848, VcpuCount: 96, MemGb: 768},
	"i3en.metal":    {OnDemandUsdPerHour: 10.848, VcpuCount: 96, MemGb: 768},

	// Storage optimized: i4i (Intel NVMe SSD)
	"i4i.large":    {OnDemandUsdPerHour: 0.172, VcpuCount: 2, MemGb: 16},
	"i4i.xlarge":   {OnDemandUsdPerHour: 0.343, VcpuCount: 4, MemGb: 32},
	"i4i.2xlarge":  {OnDemandUsdPerHour: 0.686, VcpuCount: 8, MemGb: 64},
	"i4i.4xlarge":  {OnDemandUsdPerHour: 1.373, VcpuCount: 16, MemGb: 128},
	"i4i.8xlarge":  {OnDemandUsdPerHour: 2.746, VcpuCount: 32, MemGb: 256},
	"i4i.12xlarge": {OnDemandUsdPerHour: 4.118, VcpuCount: 48, MemGb: 384},
	"i4i.16xlarge": {OnDemandUsdPerHour: 5.491, VcpuCount: 64, MemGb: 512},
	"i4i.24xlarge": {OnDemandUsdPerHour: 8.2368, VcpuCount: 96, MemGb: 768},
	"i4i.32xlarge": {OnDemandUsdPerHour: 10.9824, VcpuCount: 128, MemGb: 1024},
	"i4i.metal":    {OnDemandUsdPerHour: 10.982, VcpuCount: 128, MemGb: 1024},

	// Storage optimized: i4g (Graviton2 NVMe SSD)
	"i4g.large":    {OnDemandUsdPerHour: 0.15444, VcpuCount: 2, MemGb: 16},
	"i4g.xlarge":   {OnDemandUsdPerHour: 0.30888, VcpuCount: 4, MemGb: 32},
	"i4g.2xlarge":  {OnDemandUsdPerHour: 0.61776, VcpuCount: 8, MemGb: 64},
	"i4g.4xlarge":  {OnDemandUsdPerHour: 1.23552, VcpuCount: 16, MemGb: 128},
	"i4g.8xlarge":  {OnDemandUsdPerHour: 2.47104, VcpuCount: 32, MemGb: 256},
	"i4g.16xlarge": {OnDemandUsdPerHour: 4.94208, VcpuCount: 64, MemGb: 512},

	// Storage optimized: im4gn (Graviton2 NVMe SSD)
	"im4gn.large":    {OnDemandUsdPerHour: 0.1819, VcpuCount: 2, MemGb: 8},
	"im4gn.xlarge":   {OnDemandUsdPerHour: 0.36379, VcpuCount: 4, MemGb: 16},
	"im4gn.2xlarge":  {OnDemandUsdPerHour: 0.72758, VcpuCount: 8, MemGb: 32},
	"im4gn.4xlarge":  {OnDemandUsdPerHour: 1.45517, VcpuCount: 16, MemGb: 64},
	"im4gn.8xlarge":  {OnDemandUsdPerHour: 2.91034, VcpuCount: 32, MemGb: 128},
	"im4gn.16xlarge": {OnDemandUsdPerHour: 5.82067, VcpuCount: 64, MemGb: 256},

	// Storage optimized: is4gen (Graviton2 dense NVMe SSD)
	"is4gen.medium":  {OnDemandUsdPerHour: 0.14408, VcpuCount: 1, MemGb: 6},
	"is4gen.large":   {OnDemandUsdPerHour: 0.28815, VcpuCount: 2, MemGb: 12},
	"is4gen.xlarge":  {OnDemandUsdPerHour: 0.5763, VcpuCount: 4, MemGb: 24},
	"is4gen.2xlarge": {OnDemandUsdPerHour: 1.1526, VcpuCount: 8, MemGb: 48},
	"is4gen.4xlarge": {OnDemandUsdPerHour: 2.3052, VcpuCount: 16, MemGb: 96},
	"is4gen.8xlarge": {OnDemandUsdPerHour: 4.6104, VcpuCount: 32, MemGb: 192},

	// Storage optimized: d3 (dense HDD)
	"d3.xlarge":  {OnDemandUsdPerHour: 0.499, VcpuCount: 4, MemGb: 32},
	"d3.2xlarge": {OnDemandUsdPerHour: 0.999, VcpuCount: 8, MemGb: 64},
	"d3.4xlarge": {OnDemandUsdPerHour: 1.998, VcpuCount: 16, MemGb: 128},
	"d3.8xlarge": {OnDemandUsdPerHour: 3.99552, VcpuCount: 32, MemGb: 256},

	// Storage optimized: d3en (dense HDD)
	"d3en.xlarge":   {OnDemandUsdPerHour: 0.526, VcpuCount: 4, MemGb: 16},
	"d3en.2xlarge":  {OnDemandUsdPerHour: 1.051, VcpuCount: 8, MemGb: 32},
	"d3en.4xlarge":  {OnDemandUsdPerHour: 2.103, VcpuCount: 16, MemGb: 64},
	"d3en.6xlarge":  {OnDemandUsdPerHour: 3.154, VcpuCount: 24, MemGb: 96},
	"d3en.8xlarge":  {OnDemandUsdPerHour: 4.20576, VcpuCount: 32, MemGb: 128},
	"d3en.12xlarge": {OnDemandUsdPerHour: 6.30864, VcpuCount: 48, MemGb: 192},

	// CPU general: m4 (legacy, pre-Nitro)
	"m4.large":    {OnDemandUsdPerHour: 0.1, VcpuCount: 2, MemGb: 8},
	"m4.xlarge":   {OnDemandUsdPerHour: 0.2, VcpuCount: 4, MemGb: 16},
	"m4.2xlarge":  {OnDemandUsdPerHour: 0.4, VcpuCount: 8, MemGb: 32},
	"m4.4xlarge":  {OnDemandUsdPerHour: 0.8, VcpuCount: 16, MemGb: 64},
	"m4.10xlarge": {OnDemandUsdPerHour: 2, VcpuCount: 40, MemGb: 160},
	"m4.16xlarge": {OnDemandUsdPerHour: 3.2, VcpuCount: 64, MemGb: 256},

	// CPU compute: c4 (legacy)
	"c4.large":   {OnDemandUsdPerHour: 0.1, VcpuCount: 2, MemGb: 3.75},
	"c4.xlarge":  {OnDemandUsdPerHour: 0.199, VcpuCount: 4, MemGb: 7.5},
	"c4.2xlarge": {OnDemandUsdPerHour: 0.398, VcpuCount: 8, MemGb: 15},
	"c4.4xlarge": {OnDemandUsdPerHour: 0.796, VcpuCount: 16, MemGb: 30},
	"c4.8xlarge": {OnDemandUsdPerHour: 1.591, VcpuCount: 36, MemGb: 60},

	// CPU memory: r4 (legacy)
	"r4.large":    {OnDemandUsdPerHour: 0.133, VcpuCount: 2, MemGb: 15.25},
	"r4.xlarge":   {OnDemandUsdPerHour: 0.266, VcpuCount: 4, MemGb: 30.5},
	"r4.2xlarge":  {OnDemandUsdPerHour: 0.532, VcpuCount: 8, MemGb: 61},
	"r4.4xlarge":  {OnDemandUsdPerHour: 1.064, VcpuCount: 16, MemGb: 122},
	"r4.8xlarge":  {OnDemandUsdPerHour: 2.128, VcpuCount: 32, MemGb: 244},
	"r4.16xlarge": {OnDemandUsdPerHour: 4.256, VcpuCount: 64, MemGb: 488},
}

func PriceForInstance(instanceType string) (InstancePrice, bool) {
	p, ok := InstancePricing[instanceType]
	return p, ok
}

func PriceForInstanceOn(provider, instanceType string) (InstancePrice, bool) {
	switch provider {
	case "azure":
		p, ok := AzureInstancePricing[instanceType]
		return p, ok
	case "gcp":
		p, ok := GcpInstancePricing[instanceType]
		return p, ok
	}
	return PriceForInstance(instanceType)
}

func (p InstancePrice) EffectiveUsdPerHour(capacityType string) float64 {
	if capacityType != "spot" {
		return p.OnDemandUsdPerHour
	}
	factor := p.SpotUsdPerHourFactor
	if factor <= 0 {
		factor = SpotDefaultFactor
	}
	return p.OnDemandUsdPerHour * factor
}

func PricingTableVersion() string {
	return pricingTableVersion
}
