root = "/var/lib/buildkit"

[worker]

[worker.containerd]
    enabled = false

[worker.oci]
    enabled = true
    gc = true
    gckeepstorage = 10240000000
    snapshotter = "overlayfs"

    [[worker.oci.gcpolicy]]
    filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
    keepBytes = 5000000000
    keepDuration = 31449600

    [[worker.oci.gcpolicy]]
    all = true
    keepBytes = 10240000000
