name: cleanup_azure

on:
  schedule:
    - cron:  '0 2/24 * * *'
  workflow_dispatch:

jobs:
  cleanup-azure:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: azure secrets
        run: ci/secrets.sh
        env:
          PROVIDER: azure
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_REGION: ${{ secrets.ARM_REGION }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      - name: dependencies
        run: ci/dependencies.sh
      - name: azure cleanup
        run: ci/azure_cleanup.sh
