name: cleanup_aws_do

on:
  schedule:
    - cron:  '0 2/24 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: secrets
        run: ci/secrets.sh
        env:
          SECRETS: ${{ toJson(secrets) }}
          PROVIDER: aws
      - name: dependencies
        run: ci/dependencies.sh
      - name: cleanup
        run: ci/cleanup.sh
      - name: do secrets
        run: ci/secrets.sh
        env:
          SECRETS: ${{ toJson(secrets) }}
          PROVIDER: do
      - name: do cleanup
        run: ci/do_cleanup.sh
