name: cleanup_gcp

on:
  schedule:
    - cron:  '0 2/24 * * *'
  workflow_dispatch:

jobs:
  cleanup-gcp:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: gcp secrets
        run: ci/secrets.sh
        env:
          PROVIDER: gcp
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
      - name: dependencies
        run: ci/dependencies.sh
      - name: gcp cleanup
        run: ci/gcp_cleanup.sh
