name: cleanup_aws

on:
  schedule:
    - cron:  '0 2/24 * * *'
  workflow_dispatch:

jobs:
  test-clouds:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        provider:
          - aws
    steps:
      - name: cleanup
        run: ci/cleanup.sh
