name: daily test

on:
  schedule:
    - cron:  '0 0/24 * * *'
  workflow_dispatch:

jobs:
  test-clouds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - aws
          - azure
          - do
          - gcp
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: name
        run: echo "RACK_NAME=ci-$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: provider
        run: echo "PROVIDER=${{ matrix.provider }}" >> $GITHUB_ENV
      - name: secrets
        run: ci/secrets.sh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_REGION: ${{ secrets.ARM_REGION }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_ACCESS_ID: ${{ secrets.DIGITALOCEAN_ACCESS_ID }}
          DIGITALOCEAN_REGION: ${{ secrets.DIGITALOCEAN_REGION }}
          DIGITALOCEAN_SECRET_KEY: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
      - name: dependencies
        run: ci/dependencies.sh
      - name: cli
        run: ci/cli.sh
      - name: install last release
        run: ci/install_last_release.sh
      - name: wait
        run: sleep 300
      - name: test
        run: ci/test.sh
      - name: debug
        run: ci/debug.sh
        if: always()
      - name: uninstall
        run: ci/uninstall.sh
        if: always()
