name: daily test

env:
  VERSION: 3.0.49 # @TODO: Automate to get the latest stable tag: https://bit.ly/3krkRNN
                  # NOTE: convox update is run below so test are run on latest release

on:
  schedule:
    - cron:  '0 0/24 * * *'
  workflow_dispatch:

jobs:
  test-clouds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - aws
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: name
        run: echo "RACK_NAME=convox-ci" >> $GITHUB_ENV
      - name: provider
        run: echo "PROVIDER=aws" >> $GITHUB_ENV
      - name: secrets
        run: ci/secrets.sh
        env:
          SECRETS: ${{ toJson(secrets) }}
      - name: dependencies
        run: ci/dependencies.sh
      - name: cli
        run: ci/cli.sh
      - name: cli-update
        run: sudo convox update 
      - name: cli-config
        run: convox login console.convox.com -t ${{ secrets.CONVOX_CLI_TOKEN }}
      - name: test
        run: ci/test.sh
      - name: debug
        run: ci/debug.sh
        if: always()
